placeholders:
    placeholders:
        scripts_after:
            items:
                oro_message_queue_consumer_heartbeat: ~
    items:
        oro_message_queue_consumer_heartbeat:
            template: '@@OroMessageQueue/ConsumerHeartbeat/queue_consumer_heartbeat_js.html.twig'

